# Generated by Django 4.1.7 on 2024-05-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendship',
            options={'verbose_name': 'Друзья', 'verbose_name_plural': 'Друзья'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='default_avatar.jpg', upload_to='avatars/'),
        ),
    ]
