# Generated by Django 4.1.7 on 2023-03-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_profile', '0009_alter_profile_created_at_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(help_text='Добавьте имя', max_length=64, verbose_name='Имя'),
        ),
    ]
