# Generated by Django 4.1.7 on 2023-05-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_profile', '0011_delete_dndgame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='class_name',
            field=models.CharField(max_length=50, verbose_name='Название класса'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.IntegerField(verbose_name='Уровень'),
        ),
    ]
