# Generated by Django 4.1.7 on 2023-06-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_profile', '0012_alter_profile_class_name_alter_profile_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='charisma',
            field=models.IntegerField(verbose_name='Харизма'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='intelligence',
            field=models.IntegerField(verbose_name='Интелект'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='strength',
            field=models.IntegerField(verbose_name='Сила'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wisdom',
            field=models.IntegerField(verbose_name='Мудрость'),
        ),
    ]
