# Generated by Django 4.1.7 on 2023-06-10 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_profile', '0013_alter_profile_charisma_alter_profile_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='constitution',
            field=models.IntegerField(verbose_name='Телосложение'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dexterity',
            field=models.IntegerField(verbose_name='Ловкость'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('image', models.ImageField(help_text='Добавьте картинку', null=True, upload_to='', verbose_name='Картинка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_profile.profile', verbose_name='Персонаж')),
            ],
            options={
                'verbose_name': ('Предмет',),
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd_profile.profile', verbose_name='Персонаж')),
                ('item', models.ManyToManyField(to='dnd_profile.item', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': ('Инвентарь',),
                'verbose_name_plural': 'Инвентари',
            },
        ),
    ]
