# Generated by Django 4.1.7 on 2024-05-04 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_profile', '0014_alter_profile_constitution_alter_profile_dexterity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
