# Generated by Django 4.1.7 on 2024-05-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_profile', '0015_remove_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='race',
            field=models.CharField(choices=[('Dragonborn', 'Драконорожденный'), ('Dwarf', 'Дварф'), ('Elf', 'Эльф'), ('Gnome', 'Гном'), ('Half-Elf', 'Полуэльф'), ('Half-Orc', 'Полуорк'), ('Halfling', 'Халфлинг'), ('Human', 'Человек'), ('Tiefling', 'Тифлинг')], max_length=50),
        ),
    ]
