# Generated by Django 4.1.7 on 2024-05-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_profile', '0016_alter_profile_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='race',
            field=models.CharField(choices=[('Драконорожденный', 'Dragonborn'), ('Дварф', 'Dwarf'), ('Эльф', 'Elf'), ('Гном', 'Gnome'), ('Полуэльф', 'Half-Elf'), ('Полуорк', 'Half-Orc'), ('Халфлинг', 'Halfling'), ('Человек', 'Human'), ('Тифлинг', 'Tiefling')], max_length=50),
        ),
    ]
