# Generated by Django 4.1.7 on 2024-05-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_profile', '0017_alter_profile_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='class_name',
            field=models.CharField(choices=[('Бард', 'Bard'), ('Варвар', 'Barbarian'), ('Воин', 'Fighter'), ('Волшебник', 'Wizard'), ('Друид', 'Druid'), ('Жрец', 'Cleric'), ('Колдун', 'Warlock'), ('Монах', 'Monk'), ('Паладин', 'Paladin'), ('Плут', 'Rogue'), ('Следопыт', 'Ranger'), ('Чародей', 'Sorcerer')], max_length=50, verbose_name='Название класса'),
        ),
    ]
