# Generated by Django 4.1.7 on 2024-05-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_profile', '0019_profile_charisma_modifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='proficiency_bonus',
            field=models.IntegerField(default=2, verbose_name='Бонус владения'),
        ),
    ]
