# Generated by Django 4.1.7 on 2024-05-29 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_profile', '0021_alter_inventory_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alignment',
            field=models.CharField(choices=[('LG', 'Lawful Good'), ('NG', 'Neutral Good'), ('CG', 'Chaotic Good'), ('LN', 'Lawful Neutral'), ('N', 'Neutral'), ('CN', 'Chaotic Neutral'), ('LE', 'Lawful Evil'), ('NE', 'Neutral Evil'), ('CE', 'Chaotic Evil')], default=django.utils.timezone.now, max_length=2, verbose_name='Мировоззрение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='armor_class',
            field=models.IntegerField(default=1, verbose_name='Класс брони'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='background',
            field=models.CharField(choices=[('Acolyte', 'Acolyte'), ('Charlatan', 'Charlatan'), ('Criminal', 'Criminal'), ('Entertainer', 'Entertainer'), ('Folk Hero', 'Folk Hero'), ('Guild Artisan', 'Guild Artisan'), ('Hermit', 'Hermit'), ('Noble', 'Noble'), ('Outlander', 'Outlander'), ('Sage', 'Sage'), ('Sailor', 'Sailor'), ('Soldier', 'Soldier'), ('Urchin', 'Urchin')], default='adsdadasd', max_length=50, verbose_name='Предыстория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='backstory',
            field=models.TextField(blank=True, verbose_name='Предыстория'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bonds',
            field=models.TextField(blank=True, verbose_name='Узы'),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_hit_points',
            field=models.IntegerField(default=1, verbose_name='Текущие очки здоровья'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='equipment',
            field=models.JSONField(default=dict, verbose_name='Снаряжение'),
        ),
        migrations.AddField(
            model_name='profile',
            name='flaws',
            field=models.TextField(blank=True, verbose_name='Недостатки'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hit_points',
            field=models.IntegerField(default=1, verbose_name='Очки здоровья'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='ideals',
            field=models.TextField(blank=True, verbose_name='Идеалы'),
        ),
        migrations.AddField(
            model_name='profile',
            name='initiative',
            field=models.IntegerField(default=1, verbose_name='Инициатива'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='saving_throws',
            field=models.JSONField(default=dict, verbose_name='Спасброски'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.JSONField(default=dict, verbose_name='Навыки'),
        ),
        migrations.AddField(
            model_name='profile',
            name='speed',
            field=models.IntegerField(default=1, verbose_name='Скорость'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='temporary_hit_points',
            field=models.IntegerField(default=0, verbose_name='Временные очки здоровья'),
        ),
        migrations.AddField(
            model_name='profile',
            name='traits',
            field=models.TextField(blank=True, verbose_name='Черты'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='class_name',
            field=models.CharField(choices=[('Бард', 'Bard'), ('Варвар', 'Barbarian'), ('Воин', 'Fighter'), ('Волшебник', 'Wizard'), ('Друид', 'Druid'), ('Жрец', 'Cleric'), ('Колдун', 'Warlock'), ('Монах', 'Monk'), ('Паладин', 'Paladin'), ('Плут', 'Rogue'), ('Следопыт', 'Ranger'), ('Чародей', 'Sorcerer')], max_length=50, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='race',
            field=models.CharField(choices=[('Драконорожденный', 'Dragonborn'), ('Дварф', 'Dwarf'), ('Эльф', 'Elf'), ('Гном', 'Gnome'), ('Полуэльф', 'Half-Elf'), ('Полуорк', 'Half-Orc'), ('Халфлинг', 'Halfling'), ('Человек', 'Human'), ('Тифлинг', 'Tiefling')], max_length=50, verbose_name='Раса'),
        ),
    ]
