# Generated by Django 4.1.7 on 2024-05-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_profile', '0022_profile_alignment_profile_armor_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='armor_class',
            field=models.IntegerField(default=10, verbose_name='Класс брони'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bonds',
            field=models.TextField(blank=True, verbose_name='Привязанности'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_hit_points',
            field=models.IntegerField(default=10, verbose_name='Текущие очки здоровья'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='flaws',
            field=models.TextField(blank=True, verbose_name='Изъяны'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hit_points',
            field=models.IntegerField(default=10, verbose_name='Очки здоровья'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='initiative',
            field=models.IntegerField(default=0, verbose_name='Инициатива'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='speed',
            field=models.IntegerField(default=30, verbose_name='Скорость'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='traits',
            field=models.TextField(blank=True, verbose_name='Черты характера'),
        ),
    ]
