global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django-app'
    scrape_interval: 10s
    static_configs:
      - targets: ['web-app:8000']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']