# Generated by Django 4.1.7 on 2024-05-22 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dnd_profile', '0020_profile_proficiency_bonus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название комнаты')),
                ('status', models.CharField(choices=[('created', 'Создана комната'), ('started', 'Игра началась'), ('finished', 'Игра завершилась')], default='created', max_length=50, verbose_name='Статус игры')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Время начала игры')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения игры')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_round', models.IntegerField(default=1, verbose_name='Текущий раунд')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Время начала сессии')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения сессии')),
            ],
            options={
                'verbose_name': 'Сессия игры',
                'verbose_name_plural': 'Сессии игр',
            },
        ),
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game', verbose_name='Комната')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_users', to='dnd_profile.profile', verbose_name='Профиль игрока')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Игра-Пользователь',
                'verbose_name_plural': 'Игры-Пользователи',
            },
        ),
        migrations.CreateModel(
            name='PlayerAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50, verbose_name='Тип действия')),
                ('description', models.TextField(verbose_name='Описание действия')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время действия')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gameuser', verbose_name='Игрок')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='game.gamesession', verbose_name='Сессия игры')),
            ],
            options={
                'verbose_name': 'Действие игрока',
                'verbose_name_plural': 'Действия игроков',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='game.game', verbose_name='Комната')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_received', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Приглашение в комнату',
                'verbose_name_plural': 'Приглашения в комнату',
            },
        ),
        migrations.AddField(
            model_name='gamesession',
            name='active_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_sessions', to='game.gameuser', verbose_name='Активный игрок'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game', verbose_name='Игра'),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(through='game.GameUser', to=settings.AUTH_USER_MODEL, verbose_name='Игроки'),
        ),
    ]
