# Generated by Django 4.1.7 on 2023-04-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_profile', '0010_alter_profile_name'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='character',
            field=models.ManyToManyField(related_name='games', to='dnd_profile.profile', verbose_name='Персонаж'),
        ),
    ]
