# Generated by Django 4.1.7 on 2023-04-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='users',
        ),
    ]
