# Generated by Django 4.1.7 on 2023-05-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_game_options_remove_game_character_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameuser',
            options={'verbose_name': 'Игра-Пользователь', 'verbose_name_plural': 'Игры-Пользователи'},
        ),
    ]
