# Generated by Django 4.1.7 on 2023-06-10 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0005_alter_gameuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время завершения игры'),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(through='game.GameUser', to=settings.AUTH_USER_MODEL, verbose_name='Игроки'),
        ),
        migrations.AddField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала игры'),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('created', 'Создана комната'), ('started', 'Игра началась'), ('finished', 'Игра завершилась')], default='created', max_length=50, verbose_name='Статус игры'),
        ),
    ]
